version: 2.1

jobs: 
  saluda: 
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Hola
      - run: echo Como te encuentras
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo Bueno, me retiro
      - run: echo Nos vemos
      - run: echo Adios
      - run: echo ...

workflows:
  hello:
    jobs:
      - saluda
      - despidete